### ISSUE TITLE
Integrate OvenSpace into OvenMediaEngine Stream/player

### ISSUE THREAD

**Issue by farbhaus** [AirenSoft/OvenSpace#1]
Hi! 

I'm using OME to stream review sessions with clients.

Currently, I use it in conjunction with ZOOM for communicating. 

Would it be possible to integrate OvenSpace directly into my OME stream, so that my clients and I can talk, see each other and the stream all through the 1 Player page/stream?

Thank you

**Comment by SangwonOh** [comment]
@zcolor Hi. You can install and use OvenSpace yourself. Detailed installation and integration with your OME are described here. (https://github.com/AirenSoft/OvenSpace/blob/main/README.md)

Thanks!!

**Comment by farbhaus** [comment]
Yes,

but my question was if I can install it on the same server I have OME running and if I can integrate the meeting capabilites of ovenspace into ovenplayer or in the same page where I run ovenplayer.

Thank you

**Comment by SangwonOh** [comment]
Yes you can. OvenSpace is a web service developed using OME's WebRTC Input and Output features, and you can modify it as much as you want to create anything you want.

**Comment by farbhaus** [comment]
Thanks! I'll look into it, though it looks like it's above my skill level.
